### PR TITLE
316 cli parser tests fail in windows path error

### PR DESCRIPTION
**Pull request by pcw24601**
Fixes platform specific paths in test that cause errors in Windows.

### CODE REVIEW

**Comment by pcw24601** [comment]
Ready for review

**Review by heyhaleema — COMMENTED** [review]
Hi @pcw24601, I've had a look at the changes and I'm just wondering if this will cause issues with non-Windows operating systems? If so, I think we should use something like [`platform.system()`](https://docs.python.org/3/library/platform.html#platform.system) to concatenate either backward or forward slashes depending on the OS detected.

**Comment by pcw24601** [comment]
Hi @heyhaleema, thanks for the review. I don't think it's a problem as (1) it passes the GutHub development tests for ubuntu 3.9 and 3.10 and (2) the paths now consistently use the device-independent `pathlib.Path` objects which should take care of the platform differences (see definitions in `hazen/tests/__init__.py`). The use of `str(DIR / 'subdir')` caught me out (someone else had introduced this notation in some places in the codebase)--here the `/` operator is overloaded in `pathlib.Path` to join the paths in a device-independent fashion.

**Review by Lucrezia-Cester — COMMENTED** [review]
this makes the path platfrom-independent, tests pass so i approve the pr

**Comment by Lucrezia-Cester** [comment]
i also changed base

**Comment by Lucrezia-Cester** [comment]
this branch was also out of date with main so I merged the new release changes to avoid merge conflicts

**Review by Lucrezia-Cester — APPROVED** [review]

**Pull request merged**
