### PR TITLE
381 Simplify unit tests for ACR tasks

### PR DESCRIPTION
**Pull request by sophie22**
Use the ability to inherit unit test logic from TestClass and apply it to ACR datasets from different scanner manufacturers.

### CODE REVIEW

**Comment by tomaroberts** [comment]
@sophie22 – I've had a quick skim through this and it broadly looks fine. I'll wait for you to implement changes to #375 first because this is a merge with that.

**Comment by tomaroberts** [comment]
@sophie22 – please can you resolve merge conflict. Let me know when you want re-review. Thanks.

**Comment by sophie22** [comment]
@tomaroberts merge conflict resolved, ready for review

**Review by tomaroberts — APPROVED** [review]
Passing tests and tested on my local machine. LGTM, thanks.

**Pull request merged**
