### PR TITLE
added print statements to test results

### LINKED ISSUE #334: QMS Conformity
requirement to print the expected results and obtained result for each new hazen version to ensure we comply with ISO9001.

image
image
image

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**
I have added print statements to the test functions within the test scripts that test for the entire function. 

This should ensure that the physicists can check the results of the test functions in the terminal if they run pytest -v -s tests/
.

@tomaroberts, @heyhaleema, could you take a look at this PR and the respective issue?

@elizaGSTT can you let me know if this resolves the conformity issue?

### CODE REVIEW

**Review by YassineAzma — CHANGES_REQUESTED** [review]
Thanks for doing this, Lucrezia. Could you please also add a print statement for the slice 5 function in ACR Geometric Accuracy.

**Comment by Lucrezia-Cester** [comment]
Hi @YassineAzma, I have added this. 

Let me know if it can be merged now.

**Comment by Lucrezia-Cester** [comment]
Hi @YassineAzma, could you please approve this PR? I have added the changes you requested..

**Review by YassineAzma — APPROVED** [review]

**Comment by YassineAzma** [comment]
Sorry for the delay.

**Pull request merged**
