### PR TITLE
Adds M1 Apple Mac installation instructions

### PR DESCRIPTION
**Pull request by heyhaleema**
This PR:

- Adds M1 Apple Mac instructions to the Linux & MacOS section in README.md
- Updates the `scikit-image`, `scipy`, `psycopg-binary`, and `numpy` package versions in requirements.txt

The above resolves the issue I had with running `pip install -r requirements.txt` and enables me to complete the installation steps and run the tests.

### CODE REVIEW

**Comment by laurencejackson** [comment]
hey @heyhaleema, as with #232, could you try rolling back the scipy and numpy versions on this PR and we can merge your changes if the tests then pass.

**Comment by heyhaleema** [comment]
Quoting comment from #232 regarding SNR test assertion failure in PR checks for visibility:
> I think the issue is Ubuntu, particularly numpy* in that OS vs. macOS:
> 
> Screenshot 2022-04-27 at 11 40 55 PM
> 
> * Potentially! See [this](https://stackoverflow.com/questions/53088270/why-is-there-different-asinh-output-from-numpy-depending-on-os) and [this](https://ogeek.cn/qa/?qa=1027018/) post.

**Comment by tomaroberts** [comment]
@heyhaleema 

I see some changes to the requirements.txt and then you reverted them in response to Laurence. Not sure which version of the file you actually want in the main branch? 

As the tests are now passing, can you update the file to whichever state you want and then we can merge the PR. Thanks.

**Comment by heyhaleema** [comment]
@tomaroberts I've reverted all changes to requirements.txt and updated the PR title, so this branch should now only add the updates to README.md. Thanks to you and @laurencejackson for looking into this and #232!

**Pull request merged**
