### PR TITLE
Adds SNR test

### PR DESCRIPTION
**Pull request by heyhaleema**
This PR adds `test_two_inputs_match` to `test_snr.py`.

### CODE REVIEW

**Comment by tomaroberts** [comment]
Tests failing on SNR assertion:

image

**Comment by laurencejackson** [comment]
@heyhaleema, could you try rolling back the scipy and numpy versions, making a new commit and pushing it again?  I believe this is the only reason the build tests are failing, if they pass we can go ahead and merge your changes. 

If they do pass we should look into how we can get these package versions running on your hardware so you can continue local testing.

**Comment by heyhaleema** [comment]
I think the issue is Ubuntu, particularly numpy*  in that OS vs. macOS:

Screenshot 2022-04-27 at 11 40 55 PM

\* Potentially! See [this](https://stackoverflow.com/questions/53088270/why-is-there-different-asinh-output-from-numpy-depending-on-os) and [this](https://ogeek.cn/qa/?qa=1027018/) post.

**Comment by tomaroberts** [comment]
@heyhaleema @laurencejackson 

The tests for this branch are now passing... but I'm very confused. Basically all I did was re-run the Development tests and magically they are now passing...?!

**Comment by tomaroberts** [comment]
Have changed this to merge into `release/0.7.0` branch rather than `main` as this PR includes code changes, whereas some of the other recent PR merges into `main` were just documentation alterations.

**Review by Lucrezia-Cester — DISMISSED** [review]

**Comment by Lucrezia-Cester** [comment]
@heyhaleema This branch is not out of date, could you please merge it to the new main?

**Review by Lucrezia-Cester — APPROVED** [review]

**Pull request merged**
