### PR TITLE
360 refactor relaxometry

### PR DESCRIPTION
**Pull request by sophie22**
The most important part of refactoring was missing from the previous PR, the way of inheriting methods and attributes from the HazenTask class.

### CODE REVIEW

**Comment by tomaroberts** [comment]
@sophie22 – two of the unit tests appear to be failing. Can you look into please? Thanks.

**Comment by sophie22** [comment]
Yes, I'm trying to figure out why and how those values have changed.
Inconveniently, the T2 calculations throw a 'Segmentation fault' error on my Mac so I'm trying to think of alternative ways of testing it locally.
Suggestions are welcome.

**Comment by tomaroberts** [comment]
Sure – I'll have a look as well.

**Review by tomaroberts — APPROVED** [review]
Great, tests passing now, thanks.

**Pull request merged**
