### PR TITLE
ACR - Slice Ordering and Orientation Checks

### LINKED ISSUE #345: Manufacturer not supported (Esaote)
Esaote manufacturer not supported (scanner now under a GSTT QA contract). 
Issues with multiple tests using ACR phantom (inc SNR, geometric accuracy using wrong slices etc..). 
Test Esaote dataset available on GSTT Sharepoint (file too large to add as attachment) and can be emailed over if needed. 
Issue reported on behalf of Rebecca Thornley and David Price

### PR DESCRIPTION
**Pull request by YassineAzma**
Add function to determine if the slice order needs to be inverted or the images need to be swapped left-right to restore the expected view of the ACR phantom

This resolves #345.

Note: this is based off work on the #343 PR. Once this has been merged, I'll rebase this PR to the active hazen branch.

### CODE REVIEW

**Review by sophie22 — DISMISSED** [review]
It looks great to me, although I'm unable to comment on the correctness of the function.
The referenced 343 refactoring looks amazing too. Tiny comment for consideration is to rename the acr_tools.py file to ACRobject.py and the class from ACRTools to ACRobject (of which each instance is an ACR_obj like currently).

**Comment by tomaroberts** [comment]
I'll review this soon too Yassine. Thanks.

**Comment by tomaroberts** [comment]
@YassineAzma – I've had a quick look through the changes in this PR and it looks sensible to me. I'll revisit properly once we've merged #343.

I agree with Sophie about the naming convention, because the class is more than just a set of useful helper tools. Let's merge #343, then can you raise a new PR with the naming changes.

Can you change:
- `acr_tools.py` -> `ACRObject.py`
- `ACRTools` class -> `ACRObject`

**Review by tomaroberts — APPROVED** [review]

**Comment by RebeccaThornley** [comment]
Hi, on a recent data set the slice order inversion did not seem to work for some tests: SNR, ghosting, uniformity. 

Though inversion seem to be applied correctly for geometric accuracy, the measurements were not performed correctly/not displayed correctly on the report. 

ACR_SAG_Rotate_90_new_1017001_7
ACR_SAG_Rotate_90_new_1017001_11

**Comment by RebeccaThornley** [comment]
In relation to comment above, report showing SNR measurement made on wrong slice due to no slice order inversion

ACR_SAG_Rotate_90_ND_new_1010001_7_smoothing

**Pull request merged**
