### PR TITLE
201 bugfix remove references to sites where data originated from

### LINKED ISSUE #201: Bugfix: remove references to sites where data originated from
hazen refers to places like EastKent and other sites in the code/test data. We should remove any of these references.

### PR DESCRIPTION
**Pull request by pcw24601**
Remove references to site locations from file/directory names and anonymises all dicom files in tests\ directory.

### CODE REVIEW

**Comment by laurencejackson** [comment]
Hi @pcw24601, thanks for this contribution - could you please change the target branch of this PR to release/0.7.0? This is the branch where we will stage releases and will merge the changes together into the main branch as each release is finalised.

**Comment by pcw24601** [comment]
Hi @laurencejackson, I think I've done that now--let me know if it's OK (I'm off for a week now so there may be a delay in getting a reply).

**Comment by tomaroberts** [comment]
@pcw24601 

Thanks for this. Did you anonymise every DICOM in `tests/data`? What did you use to anonymise them and which specific tags did you alter?

**Comment by pcw24601** [comment]
@tomaroberts 

Yes--I anonymised every file using the algorithm below (very slightly adapted from [Dicognito](https://pypi.org/project/dicognito/)). A couple of points worth noting:

1. Files no longer strictly meet the DICOM standard as I created UI prefixes which I don't own and made no effort to maintain consistency with them--if two fields contained the same UI in the original files, they will have different UIs in the anonymised versions.

1. These original DICOM files are all currently in the public domain in the git history, so anonymising now is fairly weak, although better than nothing.

**Algorithm**

    Files are anonymised by:
        
        1. Replacing [UI] fields (except 'ClassUID' and 'TransferSyntaxUID')
            with new values of the form '2.datetime.counter.ramdom'.
            
        2. Setting all [PN] fields to 'Anon'
        
        3. Removing the following fields (if they exist): 
            "BranchOfService",
            "Occupation",
            "MedicalRecordLocator",
            "MilitaryRank",
            "PatientInsurancePlanCodeSequence",
            "PatientReligiousPreference",
            "PatientTelecomInformation",
            "PatientTelephoneNumbers",
            "ReferencedPatientPhotoSequence",
            "ResponsibleOrganization"
            
        4. Set the following fields to 'Anon.random_string' (if they exist):
            "AccessionNumber",
            "OtherPatientIDs",
            "FillerOrderNumberImagingServiceRequest",
            "FillerOrderNumberImagingServiceRequestRetired",
            "FillerOrderNumberProcedure",
            "PatientID",
            "PerformedProcedureStepID",
            "PlacerOrderNumberImagingServiceRequest",
            "PlacerOrderNumberImagingServiceRequestRetired",
            "PlacerOrderNumberProcedure",
            "RequestedProcedureID",
            "ScheduledProcedureStepID",
            "StudyID"
            
        5. Set the following fields to 'Anon' (if they exist):
            "RequestingService",
            "CurrentPatientLocation",
            "PatientAddress",
            "RegionOfResidence",
            "CountryOfResidence",
            "InstitutionName",
            "InstitutionAddress",
            "InstitutionalDepartmentName",
            "StationName"
            "DeviceSerialNumber"
            "ProtocolName"
            "StudyDescription"
            "PerformedProcedureStepDescription"
            "PerformedStationName"
            "PerformedStationAETitle"
            
        6. Set "DeidentificationMethod" to 'DICOGNITO_BHSCT'
            (or append if value exists).
            
        7. DICOMDIR files are skipped

**Comment by tomaroberts** [comment]
Thanks for info Paul. 

Nice, I've never seen dicognito before. Just used pydicom in the past when anonymising my own stuff.

True re: Github history, but definitely better to sort before hazen becomes more widely adopted so fewer people don't have the files on their machines.

**Comment by pcw24601** [comment]
There are definite advantages to anonymising by hand, for example, you can hunt through the private fields. However, it's a slow process especially for phantom data were it's unlikely patient data will be exposed.

**Comment by tomaroberts** [comment]
Error on my part – merged main into here, forgetting that Paul had updated the files in this PR. Hence, the files he changed were overwritten with newer files. I've force-pushed back to his previous most recent commit.

**Comment by tomaroberts** [comment]
@tomaroberts – reminder to self, merge all the other PRs into main for the next release, then merge this one last. Should be easier to confirm that file changes are stable.

**Review by tomaroberts — APPROVED** [review]
Checked across repo to ensure any old filenames have been adjusted correctly. Tested locally with pytest. GHA tests passing. LGTM.

**Pull request merged**
