### PR TITLE
ACR SNR Functionality

### LINKED ISSUE #182: [ACR1] ACR phantom – SNR function
**Is your feature request related to a problem? Please describe.**
SNR function is missing for ACR phantom 

Priority: high for ACR

### LINKED ISSUE #186: [ACR3] SNR calculation
For the SNR, two images, slice 6 and slice 7 are needed, each from two identical TRA_T1_NORMOFF acquisition. These are the floor sections of the phantom. For the subtraction method, subtract slice 6 from slice 7 and in the resulting image calculate the noise from a large circular 195-205mm^2 ROI in the phantom. On slice 6, use the same large ROI and find the mean pixel value. The final needed calculation is SNR = Slice 6 mean pixel value /Subtraction image ROI mean pixel value x sqrt(2). 
 
image

### PR DESCRIPTION
**Pull request by YassineAzma**
Adds an ACR SNR script (based on the work of Neil Heraghty) and associated unit tests that calculates the smoothed SNR for single images and the subtraction SNR for repeated acquisitions for slice 7 of the ACR phantom. The syntax to call this function in the CLI is:
 
       hazen acr_snr <folder> --subtract=<folder2> --report

An example is shown below:

       hazen acr_snr tests/data/acr/Siemens --subtract tests/data/acr/Siemens2

This is all done within the new HazenTask framework. The methodology is identical to the existing SNR function for the MagNet function, though the centroid calculation is different.
 
Resolves #182 
Resolves #186 

The results are visualised in the report. Examples are shown below:
**Single image**
image
image
**Subtraction**
image

### CODE REVIEW

**Review by Lucrezia-Cester — COMMENTED** [review]
Hi Yassine, thank you for this. Could you please add the required docpot description?

**Comment by YassineAzma** [comment]
> Hi Yassine, thank you for this. Could you please add the required docpot description?

Hi, Lucrezia. I'm not sure what you mean here. Are you referring to [--subtract = < folder2 > ] not appearing when calling hazen in the CLI?

**Comment by Lucrezia-Cester** [comment]
Hi @YassineRMH, can this be re-based to release 1.1.1?

**Comment by Lucrezia-Cester** [comment]
Hi @YassineRMH, this PR should be merged to release 1.1.1

**Comment by YassineAzma** [comment]
> Hi @YassineRMH, this PR should be merged to release 1.1.1

Hi @Lucrezia-Cester, I think I understood what you mean this time. Let me know if there's anything else you need me to do.

**Comment by Lucrezia-Cester** [comment]
@YassineRMH cheers thank you, I'll go ahead and merge

**Review by Lucrezia-Cester — APPROVED** [review]

**Pull request merged**
