### PR TITLE
Fix readthedocs

### LINKED ISSUE #251: Add Sphinx documentation

### LINKED ISSUE #252: Link documentation to ReadTheDocs hazen page
See existing page [here](https://readthedocs.org/projects/hazen/).

### PR DESCRIPTION
**Pull request by hshuaib90**
Fixes #252 

Currently missing images for tasks. Happy to add those if someone can give them to me.

See https://hazen.readthedocs.io/en/fix-readthedocs/ for working branch

### CODE REVIEW

**Comment by heyhaleema** [comment]
@Lucrezia-Cester Thanks for offering to add the missing images! This is likely because it was based on the hazen web app repo, so you'll find them [here](https://github.com/GSTT-CSC/hazen-web-app/tree/main/app/static). As discussed, I've had a look at the [Read the Docs site](https://hazen.readthedocs.io/en/fix-readthedocs/) and so once this is merged into main, the `stable` version should build successfully.

@laurencejackson Adding you as an additional reviewer onto this PR since it contains some core hazen commits. 

Should we try to set some time aside to clear out the pending PRs?

**Comment by Lucrezia-Cester** [comment]
Hi, Haleema, thank you for looking at this. @laurencejackson, @heyhaleema, Yup, just let me know when you both have some free time.

**Comment by Lucrezia-Cester** [comment]
Hi @heyhaleema, sorry for asking you to do extra work, this morning I had a chat with Haris and he asked if the commits related to the readthedocs PR could be placed in a new branch separately? 

Let me know if you are up for it otherwise I'll try to do it.

**Comment by hshuaib90** [comment]
Sorry to clarify, as this branch is for RTD - can the other commits be put into another branch

**Comment by heyhaleema** [comment]
@hshuaib90 @Lucrezia-Cester I'm happy to do the `git rebase` and `squash`/`fixup` to remove the non-RTD commits from this branch/PR.

@laurencejackson Would you like me to add the non-RTD commits to a new branch, or are these already included in another branch/PR?

@tomaroberts I'll go ahead with discarding your commits in this branch since it seems like they've been merged already.

**Review by heyhaleema — DISMISSED** [review]
Looks good 👍

**Comment by heyhaleema** [comment]
@hshuaib90 I'd approved your changes, but I've just noticed there's a merge conflict with `newdocs/source/contributors.rst`, so I can re-review once this is resolved.

**Comment by Lucrezia-Cester** [comment]
Hi @hshuaib90, could you please fix the merge conflict suggested by Haleema?

**Comment by hshuaib90** [comment]
Thanks for reminder @Lucrezia-Cester . @heyhaleema  and I had a chat last week and she is going to fix the conflict.

**Review by heyhaleema — APPROVED** [review]

**Pull request merged**
