### PR TITLE
Slice pos axis labels

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**
added axes labels to scatter figure for slice_position task, solves issue https://github.com/GSTT-CSC/hazen/issues/234

### CODE REVIEW

**Comment by Lucrezia-Cester** [comment]
Hi @heyhaleema, @laurencejackson, could you please review this PR? Thank you.

**Comment by Lucrezia-Cester** [comment]
Hi @heyhaleema, could you review this PR please?

**Review by heyhaleema — CHANGES_REQUESTED** [review]
@Lucrezia-Cester Looks good 👍

Just before I merge, could you please have a look at the check annotations and correct where necessary? For example, comment out unused packages, remove unnecessary blank lines, etc.

**Comment by Lucrezia-Cester** [comment]
@heyhaleema, I feel like this should be in another PR as this is stuff i didn't personally add for this PR. I can add this in another issue and open a PR for this

**Comment by heyhaleema** [comment]
@Lucrezia-Cester I think, ideally, every PR needs to pass our checks, regardless of whether its related to the PR-specific changes. In this case, I think if we can fix this in this PR, then it would ensure that anyone branching off `main` would have these checks passing from the start. 

Happy to contribute to this branch and do some tidying up, if that works? I'll also update this branch with merge commit to bring in changes from `main`, if that's okay, too.

**Comment by Lucrezia-Cester** [comment]
@heyhaleema ah yes, sorry, good point

**Review by heyhaleema — APPROVED** [review]

**Comment by heyhaleema** [comment]
@laurencejackson FYI, I've reviewed and approved @Lucrezia-Cester's changes, but do we want to also update the files with check annotations?

**Review by heyhaleema — APPROVED** [review]

**Comment by laurencejackson** [comment]
> @laurencejackson FYI, I've reviewed and approved @Lucrezia-Cester's changes, but do we want to also update the files with check annotations?

If you mean the warnings raised by flake8 then its not urgent. It's useful for us to fix these as we go along to ensure some code standards but I think we can go ahead and merge this once the tests have passed.

**Review by laurencejackson — APPROVED** [review]

**Pull request merged**
